name: Pull Request Opened

env:
  ACRONYM: chefs

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  do-something:
    name: Do Something
    runs-on: ubuntu-latest
    
    steps:
    - name: Some commmands
      run: |
        echo ${{ secrets.NOT_A_SECRET }} | od -c
