name: Pull Request Opened

env:
  ACRONYM: chefs

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: "Pull Request Number:"
        type: string
        required: true

jobs:
  do-something:
    name: Print Secret
    runs-on: ubuntu-latest
    
    steps:
    - name: Some commmands
      run: |
        echo "${{ secrets.NOT_A_SECRET }}" | od -c
