name: Pull Request Opened

env:
  ACRONYM: chefs

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

jobs:
  do-something:
    name: Print Secret
    runs-on: ubuntu-latest
    
    steps:
    - name: Some commmands
      run: |
        echo "${{ secrets.NOT_A_SECRET }}" | od -c
