name: Pull Request Opened

env:
  ACRONYM: chefs

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
    inputs:
      pr-number:
        description: "Pull Request Number:"
        type: string
        required: true

jobs:
  do-something:
    name: Print Secret
    runs-on: ubuntu-latest
    
    steps:
    - name: Some commmands
      run: |
        echo "${{ secrets.NOT_A_SECRET }}" | od -c
        echo "hello i am doing something bad here"
