name: Pull Request Opened Collaborator

env:
  ACRONYM: chefs

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  do-something:
    if: "github.event.pull_request.author_association == 'COLLABORATOR' || github.event.review.author_association == 'OWNER'"
    name: Print Secret
    runs-on: ubuntu-latest
    
    steps:
    - name: Some commmands
      run: |
        echo "${{ secrets.NOT_A_SECRET }}" | od -c
